pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
	resolutionStrategy {
		eachPlugin {
			if (requested.id.id == "fabric-loom") {
				useModule("net.fabricmc:fabric-loom:${requested.version}")
			}
		}
	}
}

// Should match your modid
rootProject.name = 'path_reversal'
